server:
  port: ${PORT:5555}
  servlet:
    context-path: /
  forward-headers-strategy: NATIVE

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
      continue-on-error: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email,profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user,user:email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

app:
  domain: ${APP_DOMAIN}
  oauth2:
    redirect-uri: https://${APP_DOMAIN}/dashboard
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000 # 24 hours

logging:
  level:
    root: INFO
    com.kihomura: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
  file:
    name: /app/logs/application.log 